title: <p align="center"> Sadana Abiranji </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sadanaabiranji">LinkedIn</a> |
  <a href="https://github.com/Sadana-Abiranji">GitHub</a>
  
  <br>   
  I'm working on Data Science, Spark, Machine learning & NLP related problems.
 This is a sample website creation excercise
  <br>
  </p>



theme: jekyll-theme-minimal
